# Generated by Django 5.2.5 on 2025-09-15 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0003_alter_shippingaddress_shipping_address2_order_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="amoutnt_paid",
            new_name="amount_paid",
        ),
    ]
