# Generated by Django 5.2.5 on 2025-09-25 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0004_rename_amoutnt_paid_order_amount_paid"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="date_shipped",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="shipped",
            field=models.BooleanField(default=False),
        ),
    ]
